// app/[locale]/layout.jsx
import "../globals.css";
import localFont from "next/font/local";
import { Poppins } from "next/font/google";
import { notFound } from "next/navigation";
import { NextIntlClientProvider } from "next-intl";
import Navbar from "../components/ui/Navbar";
import Footer from "../components/ui/Footer";

const LOCALES = ["en", "id"];

export function generateStaticParams() {
  return LOCALES.map((locale) => ({ locale }));
}

// Kunci supaya Next gak nerima param baru di runtime
export const dynamicParams = false;
// (opsional) full statis
export const dynamic = "error";
export const revalidate = false;

// --- (kode font dan sanitizer kamu tetap sama) ---
const quattro = localFont({
  src: [
    {
      path: "../fonts/Quattrocento-Regular.ttf",
      weight: "400",
      style: "normal",
    },
  ],
  variable: "--font-quattro",
  display: "swap",
});

const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["400", "600", "700"],
  display: "swap",
});

const minionPro = localFont({
  src: [
    {
      path: "../fonts/MinionPro-Regular.woff2",
      weight: "400",
      style: "normal",
    },
    { path: "../fonts/MinionPro-Medium.woff2", weight: "500", style: "normal" },
  ],
  variable: "--font-minion-pro",
  display: "swap",
});

const futuraDee = localFont({
  src: [{ path: "../fonts/futurano2dee.ttf", style: "normal", weight: "400" }],
  variable: "--font-futura-dee",
  display: "swap",
});

export const metadata = {
  title: "LUEVE - Custom Wedding & Engagement Rings",
  description: "Generated by create next app",
  icons: {
    icon: [{ url: "/images/logo/kepala-logo.svg", type: "image/svg+xml" }],
  },
};

// --- Sanitizer kamu tetap ---
function sanitizeIntlKeys(input, stats) {
  if (Array.isArray(input)) return input.map((v) => sanitizeIntlKeys(v, stats));
  if (input && typeof input === "object") {
    const out = {};
    for (const [k, v] of Object.entries(input)) {
      const hasDot = k.includes(".");
      const safeKey = hasDot ? k.replaceAll(".", "·") : k;
      if (hasDot) stats.count++;
      out[safeKey] = sanitizeIntlKeys(v, stats);
    }
    return out;
  }
  return input;
}

export default async function RootLayout({ children, params }) {
  const { locale } = await params;
  let messages;

  try {
    const raw = (await import(`../../messages/${locale}.json`)).default;
    const stats = { count: 0 };
    messages = sanitizeIntlKeys(raw, stats);
    if (process.env.NODE_ENV === "development" && stats.count > 0) {
      console.warn(
        `[intl] Sanitized ${stats.count} message key(s) containing '.' → '·'`
      );
    }
  } catch (error) {
    notFound();
  }

  return (
    <html lang={locale} data-scroll-behavior="smooth">
      <body
        suppressHydrationWarning
        className={`${quattro.variable} ${minionPro.variable} ${poppins.variable} ${futuraDee.variable} antialiased`}
      >
        <NextIntlClientProvider locale={locale} messages={messages}>
          <Navbar />
          <main className="pt-[96px] md:pt-[120px]">{children}</main>
          <Footer />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
